/*Creacion de claves foraneas*/

ALTER TABLE usuarios ADD FOREIGN KEY(id) REFERENCES personas(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE usuarios ADD FOREIGN KEY(id_tipo_usuario) REFERENCES perfiles(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE clientes ADD FOREIGN KEY(id) REFERENCES personas(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE prestamos ADD FOREIGN KEY(id_cliente) REFERENCES clientes(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE prestamos ADD FOREIGN KEY(id_operador) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE cuotas ADD FOREIGN KEY(id_prestamo) REFERENCES prestamos(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE pagos ADD FOREIGN KEY(id_prestamo) REFERENCES prestamos(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE detalle_pagos ADD FOREIGN KEY (id_pago) REFERENCES pagos (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE detalle_pagos ADD FOREIGN KEY (id_cuota) REFERENCES cuotas (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE detalle_pagos ADD PRIMARY KEY (id_pago,id_cuota);

