/*Creacion de claves foraneas*/

ALTER TABLE Usuarios ADD FOREIGN KEY(id) REFERENCES Personas(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Usuarios ADD FOREIGN KEY(idtipousuario) REFERENCES Perfiles(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE Clientes ADD FOREIGN KEY(id) REFERENCES Personas(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE Prestamos ADD FOREIGN KEY(idcliente) REFERENCES Clientes(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Prestamos ADD FOREIGN KEY(idoperador) REFERENCES Usuarios(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE Cuotas ADD FOREIGN KEY(idprestamo) REFERENCES Prestamos(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE Pagos AADD FOREIGN KEY(idprestamo) REFERENCES Prestamos(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE DetallePagos ADD FOREIGN KEY (idpago) REFERENCES Pagos (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE DetallePagos ADD FOREIGN KEY (idcuota) REFERENCES Cuotas (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE DetallePagos ADD PRIMARY KEY (idpago,idcuota);

